global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway'
    metrics_path: /health/metrics
    static_configs:
      - targets: ['gateway:3000']

  - job_name: 'reporter'
    metrics_path: /health/metrics
    static_configs:
      - targets: ['reporter:3001']

  - job_name: 'fb-collector'
    metrics_path: /health/metrics
    static_configs:
      - targets: ['fb-collector:3010']

  - job_name: 'ttk-collector'
    metrics_path: /health/metrics
    static_configs:
      - targets: ['ttk-collector:3020']