export const MetricsDiTokens = {
  METRIC_SERVICE: Symbol.for('METRIC_SERVICE'),
  GATEWAY_METRICS_SERVICE: Symbol.for('GATEWAY_METRICS_SERVICE'),
  COLLECTORS_METRICS_SERVICE: Symbol.for('COLLECTORS_METRICS_SERVICE'),
  REPORTER_METRICS_SERVICE: Symbol.for('REPORTER_METRICS_SERVICE'),
};
